// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zkvote.proto

package protocols_zkvote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// a protocol define a set of reuqest and responses
type SubjectRequest struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// method specific data
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubjectRequest) Reset()         { *m = SubjectRequest{} }
func (m *SubjectRequest) String() string { return proto.CompactTextString(m) }
func (*SubjectRequest) ProtoMessage()    {}
func (*SubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa3fe919df2773c, []int{0}
}

func (m *SubjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectRequest.Unmarshal(m, b)
}
func (m *SubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectRequest.Marshal(b, m, deterministic)
}
func (m *SubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectRequest.Merge(m, src)
}
func (m *SubjectRequest) XXX_Size() int {
	return xxx_messageInfo_SubjectRequest.Size(m)
}
func (m *SubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectRequest proto.InternalMessageInfo

func (m *SubjectRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *SubjectRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SubjectResponse struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// response specific data
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Subjects             []*Subject `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SubjectResponse) Reset()         { *m = SubjectResponse{} }
func (m *SubjectResponse) String() string { return proto.CompactTextString(m) }
func (*SubjectResponse) ProtoMessage()    {}
func (*SubjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa3fe919df2773c, []int{1}
}

func (m *SubjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectResponse.Unmarshal(m, b)
}
func (m *SubjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectResponse.Marshal(b, m, deterministic)
}
func (m *SubjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectResponse.Merge(m, src)
}
func (m *SubjectResponse) XXX_Size() int {
	return xxx_messageInfo_SubjectResponse.Size(m)
}
func (m *SubjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectResponse proto.InternalMessageInfo

func (m *SubjectResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *SubjectResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SubjectResponse) GetSubjects() []*Subject {
	if m != nil {
		return m.Subjects
	}
	return nil
}

type Subject struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subject) Reset()         { *m = Subject{} }
func (m *Subject) String() string { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()    {}
func (*Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa3fe919df2773c, []int{2}
}

func (m *Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subject.Unmarshal(m, b)
}
func (m *Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subject.Marshal(b, m, deterministic)
}
func (m *Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subject.Merge(m, src)
}
func (m *Subject) XXX_Size() int {
	return xxx_messageInfo_Subject.Size(m)
}
func (m *Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_Subject proto.InternalMessageInfo

func (m *Subject) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Subject) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// a protocol define a set of reuqest and responses
type IdentityRequest struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// method specific data
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityRequest) Reset()         { *m = IdentityRequest{} }
func (m *IdentityRequest) String() string { return proto.CompactTextString(m) }
func (*IdentityRequest) ProtoMessage()    {}
func (*IdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa3fe919df2773c, []int{3}
}

func (m *IdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityRequest.Unmarshal(m, b)
}
func (m *IdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityRequest.Marshal(b, m, deterministic)
}
func (m *IdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityRequest.Merge(m, src)
}
func (m *IdentityRequest) XXX_Size() int {
	return xxx_messageInfo_IdentityRequest.Size(m)
}
func (m *IdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityRequest proto.InternalMessageInfo

func (m *IdentityRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *IdentityRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type IdentityResponse struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// response specific data
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IdentityIndex        [][]byte `protobuf:"bytes,3,rep,name=identityIndex,proto3" json:"identityIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityResponse) Reset()         { *m = IdentityResponse{} }
func (m *IdentityResponse) String() string { return proto.CompactTextString(m) }
func (*IdentityResponse) ProtoMessage()    {}
func (*IdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa3fe919df2773c, []int{4}
}

func (m *IdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityResponse.Unmarshal(m, b)
}
func (m *IdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityResponse.Marshal(b, m, deterministic)
}
func (m *IdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityResponse.Merge(m, src)
}
func (m *IdentityResponse) XXX_Size() int {
	return xxx_messageInfo_IdentityResponse.Size(m)
}
func (m *IdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityResponse proto.InternalMessageInfo

func (m *IdentityResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *IdentityResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *IdentityResponse) GetIdentityIndex() [][]byte {
	if m != nil {
		return m.IdentityIndex
	}
	return nil
}

// designed to be shared between all app protocols
type MessageData struct {
	// shared between all requests
	ClientVersion        string   `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Gossip               bool     `protobuf:"varint,4,opt,name=gossip,proto3" json:"gossip,omitempty"`
	NodeId               string   `protobuf:"bytes,5,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodePubKey           []byte   `protobuf:"bytes,6,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfa3fe919df2773c, []int{5}
}

func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *MessageData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterType((*SubjectRequest)(nil), "protocols.zkvote.SubjectRequest")
	proto.RegisterType((*SubjectResponse)(nil), "protocols.zkvote.SubjectResponse")
	proto.RegisterType((*Subject)(nil), "protocols.zkvote.Subject")
	proto.RegisterType((*IdentityRequest)(nil), "protocols.zkvote.IdentityRequest")
	proto.RegisterType((*IdentityResponse)(nil), "protocols.zkvote.IdentityResponse")
	proto.RegisterType((*MessageData)(nil), "protocols.zkvote.MessageData")
}

func init() { proto.RegisterFile("zkvote.proto", fileDescriptor_dfa3fe919df2773c) }

var fileDescriptor_dfa3fe919df2773c = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xd9, 0xa6, 0x7f, 0x27, 0xb5, 0x2d, 0x8b, 0xc8, 0x0a, 0x2a, 0x21, 0x78, 0xc8, 0x29,
	0x87, 0x8a, 0x67, 0x11, 0xbc, 0x14, 0x11, 0x64, 0x05, 0xef, 0x69, 0x32, 0x94, 0xb5, 0x69, 0x36,
	0x76, 0xb6, 0x62, 0x7d, 0x0d, 0x1f, 0xc1, 0x67, 0xf1, 0xbd, 0x24, 0x9b, 0xb4, 0x4d, 0xf5, 0x5c,
	0x4f, 0xd9, 0xef, 0x97, 0xf9, 0xe6, 0x1b, 0x3e, 0xe8, 0x7f, 0xcc, 0xdf, 0xb4, 0xc1, 0x30, 0x5f,
	0x6a, 0xa3, 0xf9, 0xc8, 0x7e, 0x62, 0x9d, 0x52, 0x58, 0x72, 0x7f, 0x0e, 0x83, 0xa7, 0xd5, 0xf4,
	0x05, 0x63, 0x23, 0xf1, 0x75, 0x85, 0x64, 0xf8, 0x0d, 0xb8, 0x0b, 0x24, 0x8a, 0x66, 0x78, 0x17,
	0x99, 0x48, 0x30, 0x8f, 0x05, 0xee, 0xf8, 0x3c, 0xfc, 0xed, 0x0c, 0x1f, 0x76, 0x43, 0xb2, 0xee,
	0xe0, 0x02, 0x3a, 0x95, 0x14, 0x0d, 0x8f, 0x05, 0x3d, 0xb9, 0x91, 0xfe, 0x17, 0x83, 0xe1, 0x36,
	0x8d, 0x72, 0x9d, 0x11, 0x1e, 0x30, 0x8e, 0x5f, 0x43, 0x97, 0xca, 0x34, 0x12, 0x8e, 0xe7, 0x04,
	0xee, 0xf8, 0xf4, 0xef, 0xde, 0xcd, 0x3d, 0xdb, 0x51, 0xff, 0x16, 0x3a, 0x15, 0xe4, 0xc7, 0xd0,
	0x32, 0xca, 0xa4, 0x68, 0xcf, 0xea, 0xc9, 0x52, 0x70, 0x0f, 0xdc, 0x04, 0x29, 0x5e, 0xaa, 0xdc,
	0x28, 0x9d, 0x55, 0xa9, 0x75, 0xe4, 0xa7, 0x30, 0x9c, 0x24, 0x98, 0x19, 0x65, 0xd6, 0xff, 0x50,
	0xeb, 0x27, 0x83, 0xd1, 0x2e, 0xee, 0xf0, 0xbd, 0x5e, 0xc2, 0x91, 0xaa, 0xe2, 0x26, 0x59, 0x82,
	0xef, 0xb6, 0xdc, 0xbe, 0xdc, 0x87, 0xfe, 0x37, 0x03, 0xb7, 0xb6, 0xbc, 0x70, 0xc5, 0xa9, 0xc2,
	0xcc, 0x3c, 0xe3, 0x92, 0x8a, 0xde, 0xca, 0x4e, 0xf7, 0x21, 0x3f, 0x83, 0x9e, 0x51, 0x0b, 0x24,
	0x13, 0x2d, 0x72, 0x9b, 0xeb, 0xc8, 0x1d, 0xe0, 0x03, 0x68, 0xa8, 0x44, 0x38, 0xd6, 0xd8, 0x50,
	0x09, 0x3f, 0x81, 0xf6, 0x4c, 0x13, 0xa9, 0x5c, 0x34, 0x3d, 0x16, 0x74, 0x65, 0xa5, 0x0a, 0x9e,
	0xe9, 0x04, 0x27, 0x89, 0x68, 0xd9, 0xd9, 0x4a, 0xf1, 0x0b, 0x80, 0xe2, 0xf5, 0xb8, 0x9a, 0xde,
	0xe3, 0x5a, 0xb4, 0x3d, 0x16, 0xf4, 0x65, 0x8d, 0x70, 0x0e, 0x4d, 0x52, 0xb3, 0x4c, 0x74, 0xec,
	0x1f, 0xfb, 0x9e, 0xb6, 0x6d, 0x65, 0x57, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xc7, 0xed,
	0xfe, 0x4a, 0x03, 0x00, 0x00,
}
