// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subject.proto

package protocols_p2p

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// a protocol define a set of reuqest and responses
type SubjectRequest struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// method specific data
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubjectRequest) Reset()         { *m = SubjectRequest{} }
func (m *SubjectRequest) String() string { return proto.CompactTextString(m) }
func (*SubjectRequest) ProtoMessage()    {}
func (*SubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{0}
}

func (m *SubjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectRequest.Unmarshal(m, b)
}
func (m *SubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectRequest.Marshal(b, m, deterministic)
}
func (m *SubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectRequest.Merge(m, src)
}
func (m *SubjectRequest) XXX_Size() int {
	return xxx_messageInfo_SubjectRequest.Size(m)
}
func (m *SubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectRequest proto.InternalMessageInfo

func (m *SubjectRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *SubjectRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SubjectResponse struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// response specific data
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Subjects             []*Subject `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SubjectResponse) Reset()         { *m = SubjectResponse{} }
func (m *SubjectResponse) String() string { return proto.CompactTextString(m) }
func (*SubjectResponse) ProtoMessage()    {}
func (*SubjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{1}
}

func (m *SubjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectResponse.Unmarshal(m, b)
}
func (m *SubjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectResponse.Marshal(b, m, deterministic)
}
func (m *SubjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectResponse.Merge(m, src)
}
func (m *SubjectResponse) XXX_Size() int {
	return xxx_messageInfo_SubjectResponse.Size(m)
}
func (m *SubjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectResponse proto.InternalMessageInfo

func (m *SubjectResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *SubjectResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SubjectResponse) GetSubjects() []*Subject {
	if m != nil {
		return m.Subjects
	}
	return nil
}

type Subject struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subject) Reset()         { *m = Subject{} }
func (m *Subject) String() string { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()    {}
func (*Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{2}
}

func (m *Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subject.Unmarshal(m, b)
}
func (m *Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subject.Marshal(b, m, deterministic)
}
func (m *Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subject.Merge(m, src)
}
func (m *Subject) XXX_Size() int {
	return xxx_messageInfo_Subject.Size(m)
}
func (m *Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_Subject proto.InternalMessageInfo

func (m *Subject) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Subject) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// designed to be shared between all app protocols
type MessageData struct {
	// shared between all requests
	ClientVersion        string   `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Gossip               bool     `protobuf:"varint,4,opt,name=gossip,proto3" json:"gossip,omitempty"`
	NodeId               string   `protobuf:"bytes,5,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodePubKey           []byte   `protobuf:"bytes,6,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{3}
}

func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *MessageData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterType((*SubjectRequest)(nil), "protocols.p2p.SubjectRequest")
	proto.RegisterType((*SubjectResponse)(nil), "protocols.p2p.SubjectResponse")
	proto.RegisterType((*Subject)(nil), "protocols.p2p.Subject")
	proto.RegisterType((*MessageData)(nil), "protocols.p2p.MessageData")
}

func init() { proto.RegisterFile("subject.proto", fileDescriptor_3181af8fcb9beccf) }

var fileDescriptor_3181af8fcb9beccf = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xd9, 0xa6, 0x7f, 0x27, 0xb6, 0xc2, 0x20, 0x65, 0x11, 0x91, 0x10, 0x3c, 0xe4, 0x94,
	0x43, 0xbc, 0x7a, 0x11, 0xbc, 0x88, 0x08, 0xb2, 0x82, 0xf7, 0x34, 0x19, 0xea, 0x4a, 0x9b, 0x5d,
	0x3b, 0xdb, 0x83, 0x0f, 0xe3, 0xe3, 0xf8, 0x5e, 0xd2, 0xcd, 0xb6, 0x4d, 0xbd, 0x7b, 0xca, 0x7c,
	0xbf, 0xf9, 0x66, 0xe6, 0xcb, 0xc2, 0x94, 0xb7, 0x8b, 0x0f, 0xaa, 0x5c, 0x6e, 0x37, 0xc6, 0x19,
	0x9c, 0xfa, 0x4f, 0x65, 0x56, 0x9c, 0xdb, 0xc2, 0xa6, 0xef, 0x30, 0x7b, 0x6d, 0xfb, 0x8a, 0x3e,
	0xb7, 0xc4, 0x0e, 0xef, 0x20, 0x5e, 0x13, 0x73, 0xb9, 0xa4, 0x87, 0xd2, 0x95, 0x52, 0x24, 0x22,
	0x8b, 0x8b, 0xcb, 0xfc, 0x64, 0x2c, 0x7f, 0x3e, 0x3a, 0x54, 0xd7, 0x8e, 0x12, 0x46, 0x41, 0xca,
	0x5e, 0x22, 0xb2, 0x89, 0xda, 0xcb, 0xf4, 0x5b, 0xc0, 0xf9, 0xe1, 0x14, 0x5b, 0xd3, 0x30, 0xfd,
	0xd7, 0x2d, 0x2c, 0x60, 0x1c, 0xfe, 0x9a, 0x65, 0x94, 0x44, 0x59, 0x5c, 0xcc, 0xff, 0x2c, 0xdd,
	0x27, 0x39, 0xf8, 0xd2, 0x7b, 0x18, 0x05, 0x88, 0x17, 0x30, 0x70, 0xda, 0xad, 0xc8, 0x07, 0x9a,
	0xa8, 0x56, 0x60, 0x02, 0x71, 0x4d, 0x5c, 0x6d, 0xb4, 0x75, 0xda, 0x34, 0xe1, 0x64, 0x17, 0xa5,
	0x3f, 0x02, 0xe2, 0x4e, 0x5a, 0xbc, 0x81, 0x69, 0xb5, 0xd2, 0xd4, 0xb8, 0x37, 0xda, 0xf0, 0x6e,
	0xa6, 0xdd, 0x77, 0x0a, 0xf1, 0x0a, 0x26, 0x4e, 0xaf, 0x89, 0x5d, 0xb9, 0xb6, 0x7e, 0x6b, 0xa4,
	0x8e, 0x00, 0x67, 0xd0, 0xd3, 0xb5, 0x8c, 0xfc, 0x60, 0x4f, 0xd7, 0x38, 0x87, 0xe1, 0xd2, 0x30,
	0x6b, 0x2b, 0xfb, 0x89, 0xc8, 0xc6, 0x2a, 0xa8, 0x1d, 0x6f, 0x4c, 0x4d, 0x8f, 0xb5, 0x1c, 0x78,
	0x6f, 0x50, 0x78, 0x0d, 0xb0, 0xab, 0x5e, 0xb6, 0x8b, 0x27, 0xfa, 0x92, 0xc3, 0x44, 0x64, 0x67,
	0xaa, 0x43, 0x10, 0xa1, 0xcf, 0x7a, 0xd9, 0xc8, 0x91, 0xef, 0xf8, 0x7a, 0x31, 0xf4, 0x6f, 0x75,
	0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x40, 0xba, 0x15, 0x2e, 0x3b, 0x02, 0x00, 0x00,
}
